language: node_js
node_js:
  - "8"
before_script:
  - yarn run lint
install:
  - yarn install
  - yarn globl add codecov
script:
  - yarn run test
  - codecov
after_success:
  - yarn run semantic-release
